# Use postgres/example user/password credentials
version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: ./compose/DockerFile
    env_file:
      - apps/server-hire/dist/config/.env.production
    ports:
      - 80:80
    expose:
      - 80
    command:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: relax_db
    volumes:
      - /data/postgresql/data/db:/data/db
    ports:
      - '5432:5432'
