# Use postgres/example user/password credentials
version: '3.1'
services:
  realx_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - /data/postgresql/data/db:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
