# Use postgres/example user/password credentials
version: '3.1'
services:
  server-hire:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - '3000:3000'
    command: yarn start:pm2
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: relax_db
      POSTGRES_PASSWORD: example
    volumes:
      - /data/postgresql/data/db:/data/db
    ports:
      - '5432:5432'
